### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by ZhouAo-ZA** [pallashadow/SuperGlue-pytorch#2]
im trying to run the train,but got some error:
 
  File "mtrand.pyx", line 743, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1260, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high
what folder is handfile，i create a empty folder named handfile ,is a empty path?

**Comment by pallashadow** [comment]
it seems like a numpy error?

**Comment by pallashadow** [comment]
"handfile" folder is an image set used to simulate occlusion objects in my task. Just keep it empty.

**Comment by ZhouAo-ZA** [comment]
> it seems like a numpy error?

我解决了这个问题，但是有遇到了新的问题：
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    for i, data in enumerate(train_loader):
  File "D:\python-project\anaconda\envs\deeplearning\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "D:\python-project\anaconda\envs\deeplearning\lib\site-packages\torch\utils\data\dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\python-project\anaconda\envs\deeplearning\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "D:\python-project\anaconda\envs\deeplearning\lib\site-packages\torch\utils\data\_utils\collate.py", line 74, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "D:\python-project\anaconda\envs\deeplearning\lib\site-packages\torch\utils\data\_utils\collate.py", line 74, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "D:\python-project\anaconda\envs\deeplearning\lib\site-packages\torch\utils\data\_utils\collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [300, 2] at entry 0 and [210, 2] at entry 2


我使用的coco数据集，其他设置遵循代码里的default，你的示例运行里没有指定online模式为1，我修改了default为1，然后没有其他改动，但是跑不起来

**Comment by ZhouAo-ZA** [comment]
> > it seems like a numpy error?
> 
> 我解决了这个问题，但是有遇到了新的问题：
> Traceback (most recent call last):
> File "train.py", line 219, in
> for i, data in enumerate(train_loader):
> File "D:\python-project\anaconda\envs\deeplearning\lib\site-packages\torch\utils\data\dataloader.py", line 345, in **next**
> data = self._next_data()
> File "D:\python-project\anaconda\envs\deeplearning\lib\site-packages\torch\utils\data\dataloader.py", line 385, in _next_data
> data = self._dataset_fetcher.fetch(index) # may raise StopIteration
> File "D:\python-project\anaconda\envs\deeplearning\lib\site-packages\torch\utils\data_utils\fetch.py", line 47, in fetch
> return self.collate_fn(data)
> File "D:\python-project\anaconda\envs\deeplearning\lib\site-packages\torch\utils\data_utils\collate.py", line 74, in default_collate
> return {key: default_collate([d[key] for d in batch]) for key in elem}
> File "D:\python-project\anaconda\envs\deeplearning\lib\site-packages\torch\utils\data_utils\collate.py", line 74, in
> return {key: default_collate([d[key] for d in batch]) for key in elem}
> File "D:\python-project\anaconda\envs\deeplearning\lib\site-packages\torch\utils\data_utils\collate.py", line 55, in default_collate
> return torch.stack(batch, 0, out=out)
> RuntimeError: stack expects each tensor to be equal size, but got [300, 2] at entry 0 and [210, 2] at entry 2
> 
> 我使用的coco数据集，其他设置遵循代码里的default，你的示例运行里没有指定online模式为1，我修改了default为1，然后没有其他改动，但是跑不起来

我怀疑是batchsize的问题，当我设置batchsize为1，他确实可以run起来,但是大多数loss都是nan：
Epoch [0/20], Step [230/3734], Loss: nan
data time: 0.07, forward time: 0.07, loss time: 0.01, back time: 0.07
并且在一段时间后会报错：
Traceback (most recent call last):
  File "train.py", line 230, in <module>
    epoch_loss += Loss.item()
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by pallashadow** [comment]
Thank you. Zero padding bug fixed. I forgot to add it when change to official implement superpoint. I recommend you to use offline mode training, after check the data_builder in debug mode.

**Comment by ZhouAo-ZA** [comment]
thank you ！I have successfully run the training code, and the calculation speed is very fast, the effect is very good
