### ISSUE TITLE
i get this devision by zero errors

### ISSUE THREAD

**Issue by artiumb** [pallashadow/SuperGlue-pytorch#3]
H, thanks for adding superpoint + superglue training code 👍  , im  trying to run it ,
first i run the data_builder.py, and encounter these issues:
1.
C:\Users\artuser\SuperGlue-pytorch-improved\dataset\data_builder.py:37: RuntimeWarning: invalid value encountered in multiply
  shift_x = np.sqrt(1/x+1)*x+1/2*np.log((2*np.sqrt(1/x+1)+2)*x+1) # distance integrate of model y
its not an actual error since the code keeps running, but i would like to understand what is the purpose of this function.

2. gpu memory alloc problem ( i only have 4 Gig), seems smaller batch size solved the problem.

**Comment by pallashadow** [comment]
I warped the picture as it looks like a book page curve. It is a curve function. If you train it as a SLAM task, you should rewrite the databuilder.

**Comment by artiumb** [comment]
yes thanks i probably will rewrite.
