### ISSUE TITLE
images dumps in \dump_match_pairs are not the same image think its a bug

### ISSUE THREAD

**Issue by artiumb** [pallashadow/SuperGlue-pytorch#4]
i looked at the dump folder that should create the image with its warped version and the matching points and 
in many cases the transformed image are another image that doesnt match the original one,
im afraid its also like this in the training since it reads the image and the warped image from data[] struct:

				image0 = cv2.imread(data['image_file'][0], cv2.IMREAD_GRAYSCALE).astype(np.float32)
				image1 = cv2.imread(data['warped_file'][0], cv2.IMREAD_GRAYSCALE).astype(np.float32)
the same data[] is used for training

examples of the dumped images pairs:

![3_999_matches](https://user-images.githubusercontent.com/25672069/97783539-28047f00-1ba1-11eb-9197-b347bfb8ce21.png)
![1_2999_matches](https://user-images.githubusercontent.com/25672069/97783546-32bf1400-1ba1-11eb-9b2e-9721f9b9bffc.png)

**Comment by pallashadow** [comment]
There are 1/2 negative sample, with empty matching point.

**Comment by artiumb** [comment]
Hi thanks alot,, i dont really understand why you need negative samples( without mathcing points), youre not really using it in a contrastive loss training, anyway i have
another Question regarding your code, what is the "hand path" ?
when i train in online mode there is no way to ignote the hand file loading so it throws out an error, so i want to slightly modify the code i try to run, since i dont have those hand files i dont really understand what it does,
are you trying to do some type of augmentation using mask of hand images on top of the warped image
i didnt really understand since you do alot of remapping there after, can i train it without the hand masks at all?

**Comment by pallashadow** [comment]
i think you can simply set handpath=None.

**Comment by pallashadow** [comment]
The model would match a lot of irrelevant points on any pair of image at my first try. I fix it by encouraging the model returning empty matrix on negative pairs. I don't know whether MagicLeap did it or not, since the official method is unseen.

**Comment by artiumb** [comment]
ok i understand,thanks.
 and why didnt you include the superpoint net to train along with the superglue in an end to end manner, i think it mat also improve your point detection,did you ty it?
 ill try that but im doing this for a different purpuse and dataset.

**Comment by pallashadow** [comment]
In my project, I used https://github.com/eric-yyjau/pytorch-superpoint to train my version of superpoint. I am afraid SuperGlue definitely cannot be trained end2end with Superpoint, according to https://www.youtube.com/watch?v=u7Yo5EtOATQ.

**Comment by pallashadow** [comment]
This paper is helpful. 
Melekhov, Iaroslav, et al. "Image Stylization for Robust Features." arXiv preprint arXiv:2008.06959 (2020).

**Comment by artiumb** [comment]
Thanks , i will check it out. I have one more question , the superpoint
weights that you uploaded to github, ate they the original weight s from
the superpoint official repo or its fine tuned weights that you trained on
your dataset?

**Comment by pallashadow** [comment]
> Thanks , i will check it out. I have one more question , the superpoint weights that you uploaded to github, ate they the original weight s from the superpoint official repo or its fine tuned weights that you trained on your dataset?

the original one

**Comment by artiumb** [comment]
thanks,
another thing please , in evaluation code ,something missing in the project is those 2 functions and the 
 spObj
 spPostProcess
from those 2 libraries:
			from utils.model.superpoint.superpoint_init import spObj
			from utils.model.superpoint.superpoint_utils import spPostProcess

where are these taken from? , didnt find it in superpoint git neither...

**Comment by pallashadow** [comment]
> thanks,
> another thing please , in evaluation code ,something missing in the project is those 2 functions and the
> spObj
> spPostProcess
> from those 2 libraries:
> from utils.model.superpoint.superpoint_init import spObj
> from utils.model.superpoint.superpoint_utils import spPostProcess
> 
> where are these taken from? , didnt find it in superpoint git neither...

Sorry for delay. I once used an adapted Superpoint implementation from 1st official superpoint repo, which is slower and should be replaced. Just comment these two lines.
