### ISSUE TITLE
KeyError: 'shape0'

### ISSUE THREAD

**Issue by bixiaopeng0** [pallashadow/SuperGlue-pytorch#5]
你好，我想看一下训练完的模型的匹配效果，当我运行./match_pairs.py --viz出现如下报错信息，您知道怎么修改吗

`Namespace(cache=False, data_dir='assets/scannet_sample_images/', eval=False, fast_viz=False, keypoint_threshold=0.005, match_threshold=0.2, max_keypoints=1024, max_length=-1, nms_radius=4, opencv_display=False, pairs_list='assets/scannet_sample_pairs_with_gt.txt', resize=[640, 480], resize_float=False, results_dir='dump_match_pairs/', show_keypoints=False, shuffle=False, sinkhorn_iterations=20, superglue='indoor', useGPU=1, viz=True, viz_extension='png')
Will resize to 640x480 (WxH)
Running inference on device "cuda"
Loaded SuperPoint model
Loaded SuperGlue model ("/data/mycode/SuperGlue-pytorch/checkpoints/model_epoch_17.pth" weights)
Looking for data in directory "assets/scannet_sample_images"
Will write matches to directory "dump_match_pairs"
Will write visualization images to directory "dump_match_pairs"
Traceback (most recent call last):
  File "./match_pairs.py", line 275, in <module>
    pred = matching({'image0': inp0.to(device), 'image1': inp1.to(device)})
  File "/home/XX/miniconda3/envs/hloc_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/mycode/SuperGlue-pytorch/models/matching.py", line 85, in forward
    pred2 = self.superglue(data)
  File "/home/XX/miniconda3/envs/hloc_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/mycode/SuperGlue-pytorch/models/superglue.py", line 289, in forward
    kpts0 = normalize_keypoints(kpts0, data['shape0'])
KeyError: 'shape0'`

**Comment by wlh-coder** [comment]
您好，请问您的的data_builder.py 跑通了吗？用的什么数据集？
祝学术顺利～

**Comment by pallashadow** [comment]
The training dataset is a private one for book retrieval. I think https://github.com/gouthamvgk/SuperGlue_training would be a better practice.
