### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by ycjing** [pallashadow/SuperGlue-pytorch#6]
Hi @pallashadow 

Thank you so much for providing such wonderful codes! I have one quick question. I wonder how to quantitatively evaluate the model and compare the results with those in the SuperGlue paper. Thank you! Wish you all the best!

Best,
Yongcheng

**Comment by pallashadow** [comment]
The training dataset is a private one for book retrieval. I think https://github.com/gouthamvgk/SuperGlue_training would be a better practice.
