### ISSUE TITLE
which dataset for training

### ISSUE THREAD

**Issue by xiezhiqing0112** [pallashadow/SuperGlue-pytorch#7]
hello! thanks for your code! I would like to know about your training set. Could you please tell me which dataset you use?In data_builder.py you seem to use seq dataset??

**Comment by zongt-yu** [comment]
hi, What is the training dataset?thank you very much

**Comment by pallashadow** [comment]
The training dataset is a private one for book retrieval. I think https://github.com/gouthamvgk/SuperGlue_training would be a better practice.
